### ISSUE TITLE
URL is not a constructor in EventSource constructor when using LaunchDarkly in Next.js middleware

### ISSUE THREAD

**Issue by spicattutti** [launchdarkly/js-eventsource#23]
Heya,
I am using 
- "@launchdarkly/node-server-sdk": "9.0.6"
- "next": "14.1.3" (still mostly page router though)
- node v20.10.0
and try to fetch LD flags in a next middleware

I am seeing 
```
TypeError: URL is not a constructor\
`at new EventSource (webpack-internal:///(middleware)/../../node_modules/launchdarkly-eventsource/lib/eventsource.js:74:25
```
I made sure that the client is created and it's initialization is awaited.
LD so far works in different browser- and server contexts (e.g. app router route handlers).

Any idea what could be the problem and a possible workaround?

**Comment by kinyoklion** [comment]
Hello @spicattutti,

It appears that middleware only supports the "Edge" runtime. Meaning it doesn't have complete support for all the node APIs.
https://nextjs.org/docs/app/building-your-application/routing/middleware#runtime

My guess here is an incompatibility in URL construction/imports. You may be able to implement a polyfill to work around it. You could also try polling to see if any other incompatibilities become apparent.

I am not sure if the server SDK would be the best match for this. If these are short-lived, then an alternate approach may be better.

For instance our edge SDKs access flag data from a edge provider specific key-value store. In that way they don't have to initialize a stream or poll for every request. (If this application is targeting vercel, then you may be able to use the vercel SDK https://github.com/launchdarkly/js-core/tree/main/packages/sdk/vercel)

Thank you,
Ryan

**Comment by spicattutti** [comment]
Thanks a lot for the clarification Ryan

**Comment by kinyoklion** [comment]
@spicattutti If you need this feature I would recommend contacting our support team and requesting the feature. You can also create a github issue.
