### ISSUE TITLE
Provide support in typescript.

### ISSUE THREAD

**Issue by shubham-jasani** [launchdarkly/js-eventsource#32]
Create this package (https://www.npmjs.com/package/launchdarkly-eventsource/v/2.0.3) with the typescript as well.

Currently, we need to create `launchdarkly-eventsource.d.ts` file manually.

It would be great if you create package with @types/launchdarkly-eventsource.

**Comment by kinyoklion** [comment]
Hello @shubham-jasani,

Thank you for the request. Eventually we are planning on migrating this implementation to TypeScript, and at that point it will have type definitions. There is not currently a timeline for this development.

_Filed internally as SDK_716_

**Comment by shubham-jasani** [comment]
Okay. Thank you for the answer.
